name: Bump pslrm lockfile

on:
  workflow_dispatch:
  schedule:
    - cron: "42 6 * * 5"
      timezone: "Asia/Tokyo"

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Update lockfile and create pull request
        uses: krymtkts/pslrm-bump-action@v0.0.1
        with:
          # NOTE: GITHUB_TOKEN cannot invoke GitHub Actions workflows. If you want to trigger workflows, close and reopen the pull request after it's created.
          github-token: ${{ secrets.GITHUB_TOKEN }}
